
INSERT INTO USER (ID, USERNAME, PASSWORD, OWNERNAME, EMAIL, ACTIVATED) VALUES (1, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'enabled@user.com', 1);
INSERT INTO USER (ID, USERNAME, PASSWORD, OWNERNAME, EMAIL, ACTIVATED) VALUES (2, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'disabled@user.com', 0);

INSERT INTO AUTHORITY (ID,NAME) VALUES (1,'ROLE_MERCHANT');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);

